Training started...
Error executing job with overrides: []                                                                                                           
Traceback (most recent call last):
  File "/home/khanhnt/Khiem/MyBachelorThesis/train.py", line 284, in <module>
    main()
  File "/home/khanhnt/.conda/envs/naim/lib/python3.9/site-packages/hydra/main.py", line 90, in decorated_main
    _run_hydra(
  File "/home/khanhnt/.conda/envs/naim/lib/python3.9/site-packages/hydra/_internal/utils.py", line 394, in _run_hydra
    _run_app(
  File "/home/khanhnt/.conda/envs/naim/lib/python3.9/site-packages/hydra/_internal/utils.py", line 457, in _run_app
    run_and_report(
  File "/home/khanhnt/.conda/envs/naim/lib/python3.9/site-packages/hydra/_internal/utils.py", line 222, in run_and_report
    raise ex
  File "/home/khanhnt/.conda/envs/naim/lib/python3.9/site-packages/hydra/_internal/utils.py", line 219, in run_and_report
    return func()
  File "/home/khanhnt/.conda/envs/naim/lib/python3.9/site-packages/hydra/_internal/utils.py", line 458, in <lambda>
    lambda: hydra.run(
  File "/home/khanhnt/.conda/envs/naim/lib/python3.9/site-packages/hydra/_internal/hydra.py", line 132, in run
    _ = ret.return_value
  File "/home/khanhnt/.conda/envs/naim/lib/python3.9/site-packages/hydra/core/utils.py", line 260, in return_value
    raise self._return_value
  File "/home/khanhnt/.conda/envs/naim/lib/python3.9/site-packages/hydra/core/utils.py", line 186, in run_job
    ret.return_value = task_function(task_cfg)
  File "/home/khanhnt/Khiem/MyBachelorThesis/train.py", line 280, in main
    train(config.default)
  File "/home/khanhnt/Khiem/MyBachelorThesis/train.py", line 105, in train
    output = model(features)
  File "/home/khanhnt/.conda/envs/naim/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/khanhnt/.conda/envs/naim/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/khanhnt/Khiem/MyBachelorThesis/src/models/naim.py", line 341, in forward
    return self.naim(x)
  File "/home/khanhnt/.conda/envs/naim/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/khanhnt/.conda/envs/naim/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/khanhnt/Khiem/MyBachelorThesis/src/models/naim.py", line 321, in forward
    embeddings = encoder_layer(embeddings, mask=masks, mask2=masks2)
  File "/home/khanhnt/.conda/envs/naim/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/khanhnt/.conda/envs/naim/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/khanhnt/Khiem/MyBachelorThesis/src/models/naim.py", line 220, in forward
    inp_x = self.layer_norm_1(x)
  File "/home/khanhnt/.conda/envs/naim/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/khanhnt/.conda/envs/naim/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/khanhnt/.conda/envs/naim/lib/python3.9/site-packages/torch/nn/modules/normalization.py", line 217, in forward
    return F.layer_norm(
  File "/home/khanhnt/.conda/envs/naim/lib/python3.9/site-packages/torch/nn/functional.py", line 2910, in layer_norm
    return torch.layer_norm(
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
