Training started...
Error executing job with overrides: []                                                                                                                                              
[2025-04-10 11:41:18,498][__main__][INFO] - Train Epoch: 0 [0/51 (0%)]	Loss: 1.378765
Traceback (most recent call last):
  File "/home/khanhnt/Khiem/MyBachelorThesis/train.py", line 277, in main
    train(config.default)
  File "/home/khanhnt/Khiem/MyBachelorThesis/train.py", line 102, in train
    output = model(features)
  File "/home/khanhnt/.conda/envs/naim/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/khanhnt/.conda/envs/naim/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/khanhnt/Khiem/MyBachelorThesis/src/models/naim.py", line 341, in forward
    return self.naim(x)
  File "/home/khanhnt/.conda/envs/naim/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/khanhnt/.conda/envs/naim/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/khanhnt/Khiem/MyBachelorThesis/src/models/naim.py", line 309, in forward
    single_feature = torch.isnan(x[:, feature_idx]).to(torch.int64)
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.


Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
